# -*- mode: ruby -*-
# vi: set ft=ruby :

# Installs required plugins if not installed
if ARGV.include?('up')
  needed_reboot = false
  [
    'impressbox',
    'vagrant-hostmanager'
  ].each do |plugin|
    unless Vagrant.has_plugin?(plugin)
      system 'vagrant plugin install ' + plugin
      needed_reboot = true
    end
  end
  if needed_reboot
    system 'vagrant up'
    exit true
  end
  needed_reboot = nil
end

# Configure vagrant
Vagrant.configure(2) do |config|
  config.vm.box = '%box%'
  config.vm.provision :impressbox
end
